# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='itssafeCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=30)),
                ('categoryID', models.PositiveSmallIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='itssafePosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titr', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('ageRangeStart', models.SmallIntegerField(default=-1000)),
                ('ageRangeEnd', models.SmallIntegerField(default=0)),
                ('categoryCode', models.CharField(blank=True, editable=False, max_length=20)),
                ('publication_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='images/itssafe/8.png', upload_to='images/itssafe/')),
                ('audio', models.FileField(null=True, upload_to='audio/itssafe')),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('categoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itssafe.itssafeCategories')),
            ],
        ),
    ]
