# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itssafe', '0002_auto_20170127_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='itssafeposts',
            name='thumbUrl',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
