# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itssafe', '0003_itssafeposts_thumburl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itssafeposts',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/itssafe/'),
        ),
    ]
