# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoSamples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titr', models.CharField(max_length=30)),
                ('publication_date', models.DateField()),
            ],
        ),
    ]
