# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itsnormal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='itsNormal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='itsNormalPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titr', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('categoryCode', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('publication_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='images/itsnormal/8.png', upload_to='images/itsnormal/')),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('categoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itsnormal.itsNormal')),
            ],
        ),
        migrations.DeleteModel(
            name='PhotoSamples',
        ),
    ]
