# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsnormal', '0003_auto_20161123_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsnormalcategories',
            name='categoryID',
            field=models.PositiveSmallIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
