# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsnormal', '0004_itsnormalcategories_categoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsnormalposts',
            name='categoryCode',
            field=models.CharField(max_length=5),
        ),
    ]
