# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsnormal', '0005_auto_20161123_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsnormalposts',
            name='categoryCode',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
