# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsnormal', '0007_auto_20161123_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsnormalposts',
            name='audio',
            field=models.FileField(null=True, upload_to='audio/itsnormal'),
        ),
    ]
