# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsnormal', '0008_itsnormalposts_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsnormalposts',
            name='ageRangeEnd',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itsnormalposts',
            name='ageRangeStart',
            field=models.SmallIntegerField(default=-1000),
        ),
    ]
