# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsnormal', '0009_auto_20170101_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsnormalposts',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/itsnormal'),
        ),
    ]
