# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsnormal', '0010_auto_20170127_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsnormalposts',
            name='thumbImage',
            field=models.ImageField(blank=True, upload_to='images/itsnormal/thumb/'),
        ),
    ]
