# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 01:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itsnormal', '0013_itsnormalposts_thumburl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itsnormalposts',
            name='thumbUrl',
        ),
    ]
